books/urls.py
from django.urls import path, include

from . import views

app_name = 'books'

urlpatterns = [
    path('books/', views.books, name= 'books')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('homepage.urls')),     
    # path('', include('meetings.urls')),     
    # path('', include('users.urls')),        
    # path('', include('beer_calc.urls')),        
    path('', include('my_apps.urls')),        
    path('', include('password_generator.urls')),        
    path('', include('currency_calc.urls')),        
    path('', include('rubikcube.urls')),        
    path('', include('flac_mp3_tag.urls')),        
    path('', include('deploying.urls')),        
    #path('', include('tests.urls')),          
    path('', include('checklist.urls')),       
    path('', include('user_data.urls')),       
    path('', include('split_the_bills.urls')),  
    path('', include('beer_calc.urls')),        
    path('', include('books.urls')),              
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_generator/urls.py
from django.urls import path


from . import views

app_name = 'password_generator'
urlpatterns = [
    path('password_generator/', views.password_generator, name='password_generator'),
]

password_generator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404

import math
import random
import string 

# Create your views here.

class PasswordGenerate:
    def __init__(self, len_password = 0):
        self.len_password = len_password
        self.password = ""
        self._all_letters = string.ascii_letters + string.digits + string.punctuation
        self._len_all_letters = len(self._all_letters)
    
    def generate(self):
        for _ in range(self.len_password):
            _ = random.randint(0, len(self._all_letters) - 1)
            self.password += self._all_letters[_]
        return self.password

    def entropy(self):
        self.len_password = len(set(i for i in self.password))
        entropy = math.log2(self._len_all_letters ** self.len_password)
        return round(entropy, 2)



def password_generator(request):
    
    context = {"len_password": 8,
                "password_generated": None,
                "password_entropy": None,}
    
    if request.method == "POST":
        if "generate" in request.POST:
            len_password = request.POST["rangeValue"]
            len_password = int(len_password)

            password = PasswordGenerate(len_password)
            password_generated = password.generate()
            password_entropy = password.entropy()

            if 0 < password_entropy < 70:
                entropy_level = "Słabe hasło"
            elif 70 < password_entropy < 100:
                entropy_level = "Dobre hasło"
            else:
                entropy_level = "Znakomite hasło!"

            context = {"len_password": len_password,
                       "password_generated": password_generated,
                       "password_entropy": password_entropy,
                       "entropy_level": entropy_level,}
            

    return render(request= request, template_name= 'password_generator/password_generator.html', context= context)

password_generator/templates/password_generator/password_generator.html
{% extends 'my_apps/homepage_base.html' %}


{% block content %}
<div class="d-flex text-dark text-center col-11 justify-content-center align-items-center" style="margin: auto; min-height: 100vh">
    <div class="d-flex ">
        <div class="bg-body-tertiary rounded bg-light" style="padding: 1rem;">

            <div>
                <h1 class="display-1">Password Generator</h1>
            </div>

            {% if password_generated is None and password_entropy is None %}
            {% else %}
                <div style="margin-top: 3rem;">
                    <h1 class="display-6">Twoje wygenerowane hasło</h1>
                    <div class="alert alert-secondary text-dark" style="padding: 0;">
                        <label class="user-select-all h3 text-break" style="margin: 1rem;">{{ password_generated }}</label>
                    </div>
                </div>

                <div style="margin-top: 3rem; margin-bottom: 1rem;">
                    <h1 class="display-6">Entropia hasła</h1>
                    <div class="alert alert-secondary text-dark" style="padding: 0;">
                        <label class="user-select-all h3" style="margin: 1rem;">{{ password_entropy }}</label>
                    </div>
                </div>

                {% if entropy_level == "Słabe hasło" %}
                    <div class="alert alert-danger" role="alert">
                {% elif entropy_level == "Dobre hasło" %}
                    <div class="alert alert-warning" role="alert">
                {% elif entropy_level == "Znakomite hasło!" %}
                    <div class="alert alert-success" role="alert">
                {% endif %}
                        <label class="text-dark display-6">{{ entropy_level }}</label>
                    </div>

            {% endif %}

            <div style="margin-top: 3rem; margin-bottom: 3rem;">
                <h1 class="display-6">Wybierz długość hasła</h1>

                <form method="POST" action="{% url 'password_generator:password_generator' %}">
                    {% csrf_token %}
                    <div style="margin-top: 2rem;">
                        <input value="{{ len_password }}" type="range" id="rangeInput" name="rangeValue" min="8" max="40" step="1" style="width: 80%">
                        <span class="btn btn-danger" id="rangeValueDisplay">{{ len_password }}</span>
                    </div>
                    
                    <div style="margin-top: 2rem;">
                        <button type="submit" class="btn btn-success" name="generate" value="{{ rangeValue }}">Wygeneruj hasło!</button>
                    </div>

                </form>
            </div>

            <div>
                <label class="h5">Metoda obliczania entropii</label>
            </div>
            <div>
                <label class="h6">E = log2(S ** L) = L * log2(S)</label>
            </div>
            <div>
                <label class="h6">E - entropia</label>
            </div>
            <div>
                <label class="h6">S - liczba możliwych unikalnych znaków (tu: 94)</label>
            </div>
            <div>
                <label class="h6">L - liczba unikalnych znaków w haśle</label>
            </div>
            
        </div>
    </div>
</div>

<script>
    const rangeInput = document.getElementById('rangeInput');
    const rangeValueDisplay = document.getElementById('rangeValueDisplay');

    rangeInput.addEventListener('input', function() {
        rangeValueDisplay.textContent = rangeInput.value;
    });
</script>

{% endblock content %}