books/urls.py
from django.urls import path, include

from . import views

app_name = 'books'

urlpatterns = [
    path('books/', views.books, name= 'books')
]

checklist/urls.py
from django.urls import path, include

from . import views

app_name = 'checklist'

urlpatterns = [
    path('checklist/', view= views.checklist, name= 'checklist'),
    path('checklist_note/<int:id>/', view= views.note, name= 'note'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('homepage.urls')),     
    # path('', include('meetings.urls')),     
    # path('', include('users.urls')),        
    # path('', include('beer_calc.urls')),        
    path('', include('my_apps.urls')),        
    path('', include('password_generator.urls')),        
    path('', include('currency_calc.urls')),        
    path('', include('rubikcube.urls')),        
    path('', include('flac_mp3_tag.urls')),        
    path('', include('deploying.urls')),        
    #path('', include('tests.urls')),          
    path('', include('checklist.urls')),       
    path('', include('user_data.urls')),       
    path('', include('split_the_bills.urls')),  
    path('', include('beer_calc.urls')),        
    path('', include('books.urls')),              
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checklist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Note(models.Model):
    id = models.AutoField(primary_key= True)
    owner = models.ForeignKey(to= User, on_delete= models.CASCADE)
    title = models.TextField(blank= False, max_length= 50)
    content = models.JSONField(default= dict)
    created = models.DateTimeField(default= timezone.now)


    class Meta:
        verbose_name = "Note"
        verbose_name_plural = "Notes"


    def __str__(self):
        return f"{self.id}. owner = {self.owner.username}, title = {self.title}"



class InvitedToNote(models.Model):
    id = models.AutoField(primary_key= True)
    note = models.ForeignKey(to= Note, on_delete= models.CASCADE)
    invited_friend = models.ForeignKey(to= User, on_delete= models.CASCADE)


    class Meta:
        verbose_name = 'Invited to note'
        verbose_name_plural = 'Invited to note'
    

    def __str__(self):
        return f"{self.id}. {self.invited_friend} added to {self.note.title}"

beer_calc/forms.py
from django import forms


class BrixToBlgForm(forms.Form):
    brix_to_blg_field = forms.FloatField(
        help_text= 'Brix',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        ),
    )



class BlgToBrixForm(forms.Form):
    baling_to_brix_field = forms.FloatField(
        help_text= 'Baling',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        ),
    )



class BrixToAlcoholForm(forms.Form):
    brix_start_field = forms.FloatField(
        help_text= 'Brix początkowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )

    brix_end_field = forms.FloatField(
        help_text= 'Brix końcowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )



class BalingToAlcoholForm(forms.Form):
    baling_start_field = forms.FloatField(
        help_text= 'Baling początkowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )

    baling_end_field = forms.FloatField(
        help_text= 'Baling końcowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )



class CarbonationOfBeerForm(forms.Form):
    co2_field = forms.FloatField(
        help_text= 'Poziom CO2',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 2.0,
                'max': 3.5,
            }
        )
    )

    temperature_field = forms.FloatField(
        help_text= 'Temperatura piwa [°C]',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.1,
                'min': 0,
                'max': 30,
            }
        )
    )
    
    beer_volume_field = forms.FloatField(
        help_text= 'Objętość piwa [L]',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.1,
                'min': 0,
                'max': 25,
            }
        )
    )
    
    blg_start_field = forms.FloatField(
        help_text= 'Baling początkowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.1,
                'min': 0,
                'max': 30,
            }
        )
    )



class SearchForm(forms.Form):
    search_field = forms.CharField(
        help_text= "Szukaj",
        widget= forms.TextInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'type': 'search',
                'onkeyup': "search_function()",
            }
        )
    )

checklist/forms.py
from django import forms
from .models import Note



universal_class = 'form-control text-break word-wrap text-light'
universal_style = 'background-color: rgba(0,0,0,0); margin-top: 1rem; border: 2px solid gray; height: 32px; font-size: 15px;'



class NewNoteForm(forms.Form):

    new_note_field = forms.CharField(
        help_text= "Podaj tytuł nowej notatki",
        widget = forms.TextInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',
            }
        )
    )



class ChangeTitleForm(forms.Form):

    change_title_field = forms.CharField(
        widget = forms.TextInput(
            attrs= {
                'rows': 1,
                'class': universal_class + ' h1 text-center',
                'placeholder': '',
                'style': universal_style + ' resize: none;',
                "readonly": "readonly",
            }
        )
    )



class NewElementForm(forms.Form):

    type_of_element_field = forms.ChoiceField(
        help_text = "Wybierz rodzaj notatki do dodania:",
        choices = (
            ('', '---- Wybierz ----'), 
            ('1', 'Notatka tekstowa'), 
            ('2', 'Element'), 
            ('3', 'Grupa')
        ),
        widget=forms.Select(
            attrs={'class': 'form-select'}
        ),
    )

    element_field = forms.CharField(
        help_text = "Treść notatki:",
        widget = forms.TextInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',
            }
        )
    )



class ChangeTextForm(forms.Form):

    change_text_field = forms.CharField(
        widget= forms.Textarea(
            attrs= {
                'rows': 5,
                'class': universal_class,
                'placeholder': '',
                'style': universal_style.replace('height: 32px;', ''),
                "readonly": "readonly",
            }
        )
    )


    def __init__(self, *args, **kwargs):
        auto_id = kwargs.pop("auto_id", None)
        super().__init__(*args, **kwargs)
        if auto_id:
            self.fields["change_text_field"].widget.attrs["id"] = auto_id



class ChangeElementForm(forms.Form):

    change_element_field = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                'class': universal_class,
                'placeholder': '',
                'style': universal_style,
                "readonly": "readonly",
            }
        )
    )


    def __init__(self, *args, **kwargs):
        auto_id = kwargs.pop("auto_id", None)
        super().__init__(*args, **kwargs)
        if auto_id:
            self.fields["change_element_field"].widget.attrs["id"] = auto_id



class ChangeGroupForm(forms.Form):

    change_group_field = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                'class': universal_class,
                'placeholder': '',
                'style': universal_style,
                "readonly": "readonly",
            }
        )
    )


    def __init__(self, *args, **kwargs):
        auto_id = kwargs.pop("auto_id", None)
        super().__init__(*args, **kwargs)
        if auto_id:
            self.fields["change_group_field"].widget.attrs["id"] = auto_id


class ChangeElementInGroupForm(forms.Form):

    change_element_in_group_field = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                'class': universal_class,
                'placeholder': '',
                'style': universal_style,
                "readonly": "readonly",
            }
        )
    )


    def __init__(self, *args, **kwargs):
        auto_id = kwargs.pop("auto_id", None)
        super().__init__(*args, **kwargs)
        if auto_id:
            self.fields["change_element_in_group_field"].widget.attrs["id"] = auto_id



class AddToGroupForm(forms.Form):
    add_to_group_field = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                'class': universal_class.replace("text-light", "text-dark"),
                'placeholder': 'Dodaj element do grupy',
                'style': universal_style.replace("rgba(0,0,0,0)", "rgba(255,255,255,1)"),
            }
        )
    )


    def __init__(self, *args, **kwargs):
        auto_id = kwargs.pop("auto_id", None)
        super().__init__(*args, **kwargs)
        if auto_id:
            self.fields["add_to_group_field"].widget.attrs["id"] = auto_id


"""
class TitleForm(forms.ModelForm):
    class Meta:
        model = Note

        fields = ['title']

        labels = {
            'title': 'Tytuł',
        }

        widgets = {
            'title': forms.Textarea(
                attrs= {
                    'rows': 1,
                    'class': 'form-control',
                    'placeholder': 'Tytuł',
                    'style': 'resize: none; padding: 0.5rem;'
                }
            ),
        }



class ElementForm(forms.Form):
    add_element_field = forms.CharField(
        widget= forms.Textarea(

"""

checklist/templates/checklist/add_element_form.html
<form method="post" id="add_to_group-{{ idx_g }}">
    {% csrf_token %}
    <div class="d-flex gap-1">
        {{ form_field }}
        <button type="submit" id="add_to_group_button-{{ idx_g }}" name="group_id" value="{{ idx_g }}" 
        class="btn btn-success btn-sm mt-3" 
        style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
            +
        </button>
    </div>
</form>

checklist/templates/checklist/checklist.html
{% extends "my_apps/homepage_base.html" %}

            
{% comment %} 
<div class="form-floating text-dark mb-3">
    {{  }}
    <label for="id_search_field">{{ ..help_text }}</label>
</div> 

<script>
    $(document).ready(function() {
        $('#').submit(function(e) {
            e.preventDefault();
            
            const co2 = $('#').val();
            
            $.ajax({
                url: '{% url "checklist:checklist" %}',
                type: 'POST',
                data: JSON.stringify(
                    {

                    }
                ),
                contentType: 'application/json',
                headers: {
                    'X-CSRFToken': $('input[name="csrfmiddlewaretoken"]').val()
                },

                success: function(data) {
                    if (data.success) {
                    } 
                },
            });
        });
    });
</script>
{% endcomment %}

{% block content %}
<div class="col-11 mx-auto justify-content-center" style="min-height: 100vh;">
        
    <div style="border-radius: 10px; padding: 10px; border: solid 2px; max-width: 500px;" class="justify-content-center mx-auto mb-4">
        <form id="new-note-form" method="POST">
            <div class="form-floating text-dark mb-3">
                {% csrf_token %}
                {{ new_note_form.new_note_field }}
                <label for="id_new_note_field">{{ new_note_form.new_note_field.help_text }}</label>
            </div>
            <div class="justify-content-end d-flex">
                <button type="submit" class="btn btn-md btn-primary">Dodaj</button>
            </div>
        </form>
    </div>
    
    {% if all_notes %}
    <div class="text-center mb-4">
        <label class="h1">
            Twoje notatki
        </label>
    </div>
    {% endif %}
    <div id="all-notes" style="gap: 1rem;" class="justify-content-center mx-auto d-flex flex-wrap">
        {% for note in all_notes %}
            <div class="{{ note_class }}" style="{{ note_style }}">
                <a href="{% url 'checklist:note' note.id %}" style="text-decoration: none;">
                    <button class="btn btn-{{ note.color }}" style="width: 100%;" >
                        <div>
                            <label class="display-6">
                                {{ note.title }}
                            </label>
                        </div>

                        <div>
                            <label>
                                <strong>Stworzył:</strong> {{ note.owner }}<br><strong>Stworzono:</strong> {{ note.created }}
                            </label>
                        </div>
                    </button>
                </a>
            </div>
        {% empty %}
            <label class="h1">Brak utworzonych notatek</label>
        {% endfor %}
    </div>

</div>
{% endblock content %}

checklist/templates/checklist/checklist_old.html
{% extends "my_apps/homepage_base.html" %}

{% block content %}
<div class="col-11 mx-auto justify-content-center" style="min-height: 100vh;">
    
    <div class="col-11">
        <button class="btn btn-md btn-success" style="margin-bottom: 2rem;" data-bs-toggle="modal" data-bs-target="#exampleModal">Nowa notatka</button>

        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content bg-dark">

                    <form method="POST" style="margin: 0;">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Dodaj notatkę</h1>
                            <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
    
                        <div class="modal-body">
                            {{ title_form.title }}
                        </div>
    
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-md btn-primary">+ Dodaj notatkę</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

    <div>
        {% if not all_notes %}
            <div class="text-center row align-items-center" style="height: 80%;">
                <label class="display-1 m-0 p-0">Brak notatek</label>
            </div>
        {% else %}
            {% for note in all_notes %}
            <div class="justify-content-center mx-auto text-break word-wrap" style="padding: 1rem; max-width: 500px;">
                <a href="{% url 'checklist:note' note.id %}" style="text-decoration: none;">
                    <button class="btn btn-{{ note.color }}" style="width: 100%;" >
                        <div>
                            <label class="display-6">
                                {{ note.title }}
                            </label>
                        </div>

                        <div>
                            <label>
                                <strong>Stworzył:</strong> {{ note.owner }}<br><strong>Stworzono:</strong> {{ note.created }}
                            </label>
                        </div>
                    </button>
                </a>
            </div>
            {% endfor %}
        {% endif %}
    </div>

</div>
{% endblock content %}

checklist/templates/checklist/element.html
<div id="element-{{ index }}">
    <div class="d-flex gap-1">
        
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="check_uncheck_element_note" id="check_uncheck_element_note_{{ index }}" value="{{ index }}" 
                class="btn btn-{% if checked %}success{% else %}danger{% endif %}" 
                style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
                    <label>
                        {% if not checked %}
                            X
                        {% else %}
                            ✓
                        {% endif %}
                    </label>
                </button>
            </form>
        
        {{ form.change_element_field }}

        {% if is_owner %}
            <form method="POST">
                {% csrf_token %}
                <button type="submit" name="delete_element" id="delete_element-{{ index }}" value="{{ index }}" 
                class="btn btn-dark" 
                style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
                    <label>X</label>
                </button>
            </form>
        {% endif %}

    </div>
</div>

<script>
    $(document).ready(function() {
        var input_field = $("#change_element-{{ index }}")

        {% if checked %}
            input_field.addClass("text-decoration-line-through");
            input_field.removeClass("text-decoration-none");

        {% else %}
            input_field.addClass("text-decoration-none");
            input_field.removeClass("text-decoration-line-through");
        {% endif %}
    });
    
    {% if is_owner %}   
    $("input[id^='change_element-'][readonly]").removeAttr('readonly');
    {% endif %}
</script>

checklist/templates/checklist/element_in_group.html
<div id="element_in_group-{{ idx_g }}_{{ idx_e }}">
    <div class="d-flex gap-1">

        <form method="POST">
            {% csrf_token %}
            <button type="submit" id="check_uncheck_element_in_group-{{ idx_g }}_{{ idx_e }}"
                name= "check_uncheck_element_in_group" 
                value="{{ idx_g }}_{{ idx_e }}" 
                class="btn btn-{% if checked %}success{% else %}danger{% endif %}" 
                style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
                <label>
                    {% if not checked %}
                        X
                    {% else %}
                        ✓
                    {% endif %}
                </label>
            </button>
        </form>

        {{ element_in_group_form.change_element_in_group_field }}

        {% if is_owner %}
        <form method="POST">
            {% csrf_token %}
            <button type="submit" 
                name="delete_element_in_group" 
                id="delete_element_in_group-{{ idx_g }}_{{ idx_e }}" 
                value="{{ idx_g }}_{{ idx_e }}" 
                class="btn btn-dark" 
                style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
                <label>X</label>
            </button>
        </form>
        {% endif %}

    </div>
</div>

<script>
    $(document).ready(function() {
        var input_field = $("#change_element_in_group-{{ idx_g }}_{{ idx_e }}")

        {% if checked %}
            input_field.addClass("text-decoration-line-through");
            input_field.removeClass("text-decoration-none");
        {% else %}
            input_field.addClass("text-decoration-none");
            input_field.removeClass("text-decoration-line-through");
        {% endif %}
    });   
    {% if is_owner %} 
    $("input[id^='change_element_in_group-'][readonly]").removeAttr('readonly');
    {% endif %}
</script>

checklist/templates/checklist/friend_button.html
<button type="button" name="{{ del_add }}" class="{{ class }} btn btn-sm btn-{{ color }}" value="{{ friend.id }}" id="{{ friend.id }}">
    {{ friend.username }}
</button>

checklist/templates/checklist/group.html
<div id="group-{{ idx_g }}" class="mt-3">

    <div class="d-flex gap-1">

        {{ group_form.change_group_field }}

        <div class="btn-group dropstart">
            <button type="button" 
                class="btn btn-warning dropdown-toggle" 
                data-bs-toggle="dropdown" 
                aria-expanded="false"
                style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
            </button>

            <ul class="dropdown-menu border-black bg-dark">
                <div class="d-flex justify-content-center mx-auto">
                    <form method="POST">
                        {% csrf_token %}
                        <li>
                            <button type="submit" name="check_all_group" id="check_all_group" value="{{ idx_g }}" 
                                class="btn btn-sm btn-success" 
                                style="margin-top: 0rem;">
                                <label>✓ Zaznacz wszystko</label>
                            </button>
                        </li>

                        <li>
                            <button type="submit" name="uncheck_all_group" id="uncheck_all_group" value="{{ idx_g }}" 
                                class="btn btn-sm btn-danger" 
                                style="margin-top: 1rem;">
                                <label>X Odznacz wszystko</label>
                            </button>
                        </li>
                    </form>
                </div>

                {% if is_owner %}
                    <div class="d-flex justify-content-center mx-auto">
                        <li>
                            <form method="POST">
                                {% csrf_token %}
                                <button type="submit" name="delete_group" id="delete_group" value="{{ idx_g }}" 
                                    class="btn btn-sm btn-light" 
                                    style="margin-top: 2rem;"> 
                                    <label>X Usuń grupę</label>
                                </button>
                            </form>
                        </li>
                    </div>
                {% endif %}
            </ul>
        </div>

    </div>

    <div class="d-flex justify-content-start gap-1">
    </div>
    
</div>
<script>      
    {% if is_owner %}
    $("input[id^='change_group-'][readonly]").removeAttr('readonly');
    {% endif %}
</script>

checklist/templates/checklist/text_note.html
<div id="note-{{ index }}">
    <div class="d-flex gap-1">

        {{ form.change_text_field }}
        
        {% if is_owner %}
        <div>
            <form method="POST">
                {% csrf_token %}
                <button type="submit" id="delete_text_note_{{ index }}" name="delete_text_note" value="{{ index }}" 
                class="btn btn-sm btn-dark" 
                style="margin-top: 1rem; border: 2px solid black; width: 32px; height: 32px; display: flex; align-items: center; justify-content: center; padding: 0;">
                    X
                </button>
            </form>
        </div>
        {% endif %}

    </div>
</div>
<script>      
    {% if is_owner %}
    $("textarea[id^='change_text_note-'][readonly]").removeAttr('readonly');
    {% endif %}
</script>