beer_calc/urls.py
from django.urls import path, include

from . import views

app_name = 'beer_calc'

urlpatterns = [
    path('beer_calc/', views.beer_calc, name= 'beer_calc')
]

books/urls.py
from django.urls import path, include

from . import views

app_name = 'books'

urlpatterns = [
    path('books/', views.books, name= 'books')
]

my_apps/urls.py
from django.urls import path
from django.contrib import admin


from . import views

app_name = 'my_apps'
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    # path('beer_calc/', views.calc, name='beer_calc'),
    path('', views.index, name='homepage'),
    #path('meetings_calendar/', views.meetings_homepage_old, name='meetings_calendar'),
    path('meetings_calendar/', views.meetings_homepage, name='meetings_calendar'),
    path('meetings_edit_event/<str:event_id>/', views.edit_event, name='meetings_edit_event'),
    path('meetings_new_event/<str:date>/', views.new_event, name='meetings_new_event'),
    #path('meetings_new_event/', views.new_event, name='meetings_new_event'),
    #path('meetings_new_event/', views.new_event_old, name='meetings_new_event'),
    path('users_friends/', views.friends, name='users_friends'),
    path('users_log_in/', views.log_in, name='users_log_in'),
    path('users_log_out/', views.log_out, name='users_log_out'),
    path('users_register/', views.register, name='users_register'),
    path('split_homepage/', views.add_expense_group, name='split_homepage'),
    path('split_group/<int:group_id>/', views.split_group, name='split_group'), 
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('homepage.urls')),     
    # path('', include('meetings.urls')),     
    # path('', include('users.urls')),        
    # path('', include('beer_calc.urls')),        
    path('', include('my_apps.urls')),        
    path('', include('password_generator.urls')),        
    path('', include('currency_calc.urls')),        
    path('', include('rubikcube.urls')),        
    path('', include('flac_mp3_tag.urls')),        
    path('', include('deploying.urls')),        
    #path('', include('tests.urls')),          
    path('', include('checklist.urls')),       
    path('', include('user_data.urls')),       
    path('', include('split_the_bills.urls')),  
    path('', include('beer_calc.urls')),        
    path('', include('books.urls')),              
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beer_calc/models.py
from django.db import models

# Create your models here.
class BeerStyles(models.Model):
    id = models.AutoField(primary_key= True)
    style_name = models.TextField(default= "")
    max_carbonation = models.FloatField(default= 0)
    min_carbonation = models.FloatField(default= 0)

    class Meta:
        verbose_name = "Beer style"
        verbose_name_plural = "Beer styles"



class ButtonIcon(models.Model):
    id = models.AutoField(primary_key= True)
    photo = models.ImageField(upload_to= f'beer_calc_icon/')

    class Meta:
        verbose_name = "Button Icon"
        verbose_name_plural = "Button Icon"

my_apps/models.py
from django.db import models

from django.contrib.auth.models import User # powiążemy wpis z danym użytkownikiem
from django.utils import timezone

# Create your models here.

class AvailableApp(models.Model):
    id_app = models.AutoField(primary_key= True)
    app_name = models.TextField(default= '')
    app_describe = models.TextField(default= '')
    app_link = models.TextField(default= '')
    app_log_in = models.BooleanField(default= True)
    app_tutorial = models.BooleanField(default= False)

    def __str__(self) -> str:
        return f"id: {self.id_app}, name: {self.app_name}"



class AppPhotos(models.Model):
    """  500 x 500 px"""
    id_photo = models.AutoField(primary_key= True)
    id_app = models.ForeignKey(to= AvailableApp, on_delete= models.CASCADE)
    photo = models.ImageField(upload_to= f'homepage/')



class NewEventModelNew(models.Model):
    """ Wydarzenie tworzone przez użytkownika """
    owner = models.ForeignKey(User, on_delete= models.CASCADE) # powiążemy wpis z danym użytkownikiem

    event_title = models.CharField(max_length= 40, default= "")
    event_location = models.CharField(max_length= 40, default= "", blank= True)
    event_description = models.CharField(max_length= 200, default= "", blank= True)

    event_date = models.DateField()
    event_time = models.TimeField()

    date_added = models.DateTimeField(auto_now_add= True)
    
    class Meta:
        verbose_name_plural = "Events"

    def __str__(self):
        return f"{self.id}: {self.event_title}"



class InvitedToEventModelNew(models.Model):
    event = models.ForeignKey(NewEventModelNew, on_delete=models.CASCADE)
    invited_friend = models.ForeignKey(User, on_delete=models.CASCADE)
    accepted_invitation = models.BooleanField(default= False) # 1 - przyjął; 0 - brak odp./odrzucił
    decline_invitation = models.BooleanField(default= False) # 1 - odrzucił; 0 - brak odp./przyjął
    
    class Meta:
        verbose_name_plural = "Invitations to events"
        verbose_name = "Invitations to events"



class Friendship(models.Model):
    from_friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name= 'from_friends')
    to_friend = models.ForeignKey(User, on_delete= models.CASCADE, related_name= 'friends')

    all_users = User.objects.all()

    class Meta:
        # Dzięki temu ograniczeniu, nie będzie można dodać do bazy danych dwóch obiektów "Friendship" 
        # z tymi samymi wartościami pól "from_friend" i "to_friend
        unique_together = ('from_friend', 'to_friend')  

    # def __str__(self):
    #     return f"{self.from_friend} add {self.to_friend} to friend"



class AddExpenseGroup(models.Model):
    id = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, on_delete= models.CASCADE)
    expense_title = models.CharField(max_length= 100, default= "")
    status = models.CharField(max_length=15, default="Brak wydatków")

    date_added = models.DateTimeField(auto_now_add= True)


    def __str__(self):
        return f"{self.id}. {self.expense_title}"



class AddFriendToExpenseGroup(models.Model):
    id = models.AutoField(primary_key=True)
    expense_group_id = models.ForeignKey(AddExpenseGroup, on_delete= models.CASCADE)
    invited_to_group_friend = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.expense_group_id}"



class AddExpense(models.Model):
    id = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, on_delete= models.CASCADE)
    expense_group_id = models.ForeignKey(AddExpenseGroup, on_delete= models.CASCADE)

    description = models.CharField(max_length=15, default="wydatek")
    price = models.FloatField(default= 0.0)
    repaid = models.FloatField(default= 0.0)

    
    date_added = models.DateTimeField(auto_now_add= True)

    def __str__(self):
        return self.description



class AddFriendToExpense(models.Model):
    id = models.AutoField(primary_key=True)
    expense_id = models.ForeignKey(AddExpense, on_delete= models.CASCADE)
    expense_group_id = models.ForeignKey(AddExpenseGroup, on_delete= models.CASCADE)
    invited_to_expense_friend = models.ForeignKey(User, on_delete=models.CASCADE)

    # proportion or amount
    amount = models.FloatField(default= 0)  
    to_repayment = models.FloatField(default= 0)  


    # def __str__(self):
    #     return f"{self.invited_to_expense_friend} hangs {AddExpense.creator} {self.amount}/{self.to_repayment} PLN. --- {self.expense_id}" 



class OpenRegistration(models.Model):
    describe = models.TextField(default="The registration is open? (Don't create new entry, edit this one)")
    is_open = models.BooleanField(default= True)



class BeerStyles(models.Model):
    id = models.AutoField(primary_key= True)
    style_name = models.TextField(default= "")
    max_carbonation = models.FloatField(default= 0)
    min_carbonation = models.FloatField(default= 0)

    class Meta:
        verbose_name = "Beer style"
        verbose_name_plural = "Beer styles"

beer_calc/forms.py
from django import forms


class BrixToBlgForm(forms.Form):
    brix_to_blg_field = forms.FloatField(
        help_text= 'Brix',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        ),
    )



class BlgToBrixForm(forms.Form):
    baling_to_brix_field = forms.FloatField(
        help_text= 'Baling',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        ),
    )



class BrixToAlcoholForm(forms.Form):
    brix_start_field = forms.FloatField(
        help_text= 'Brix początkowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )

    brix_end_field = forms.FloatField(
        help_text= 'Brix końcowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )



class BalingToAlcoholForm(forms.Form):
    baling_start_field = forms.FloatField(
        help_text= 'Baling początkowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )

    baling_end_field = forms.FloatField(
        help_text= 'Baling końcowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 0,
                'max': 30,
            }
        )
    )



class CarbonationOfBeerForm(forms.Form):
    co2_field = forms.FloatField(
        help_text= 'Poziom CO2',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.01,
                'min': 2.0,
                'max': 3.5,
            }
        )
    )

    temperature_field = forms.FloatField(
        help_text= 'Temperatura piwa [°C]',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.1,
                'min': 0,
                'max': 30,
            }
        )
    )
    
    beer_volume_field = forms.FloatField(
        help_text= 'Objętość piwa [L]',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.1,
                'min': 0,
                'max': 25,
            }
        )
    )
    
    blg_start_field = forms.FloatField(
        help_text= 'Baling początkowe',
        widget= forms.NumberInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'step': 0.1,
                'min': 0,
                'max': 30,
            }
        )
    )



class SearchForm(forms.Form):
    search_field = forms.CharField(
        help_text= "Szukaj",
        widget= forms.TextInput(
            attrs= {
                'rows': 1,
                'class': 'form-control',
                'placeholder': '',
                'style': 'resize: none;',

                'type': 'search',
                'onkeyup': "search_function()",
            }
        )
    )

beer_calc/views.py
from django.shortcuts import render
from django.core.handlers.wsgi import WSGIRequest
from django.http import JsonResponse


from .forms import BrixToBlgForm, BlgToBrixForm, BrixToAlcoholForm, BalingToAlcoholForm, CarbonationOfBeerForm, SearchForm
from .beer_calc import BeerCalc
from .models import BeerStyles, ButtonIcon

import json

# Create your views here.
def beer_calc(request: WSGIRequest):
    
    BC = BeerCalc()

    if request.method == 'POST':

        if request.content_type == 'application/json':
            try:
                body = json.loads(request.body)
            except json.JSONDecodeError:
                return JsonResponse({'success': False, 'error': 'Invalid JSON format'}, status=400)
        else:
            body = request.POST


        form_brix = BrixToBlgForm(body)
        if form_brix.is_valid():
            brix_value = form_brix.cleaned_data['brix_to_blg_field']
            blg_value = BC.brix_to_baling(brix_value)
            return JsonResponse({'success': True, 'blg': blg_value}, status=200)
        

        form_baling = BlgToBrixForm(body)
        if form_baling.is_valid():
            baling_value = form_baling.cleaned_data['baling_to_brix_field']
            brix_value = BC.baling_to_brix(baling_value)
            return JsonResponse({'success': True, 'brix': brix_value}, status=200)
        

        form_brix_alc = BrixToAlcoholForm(body)
        if form_brix_alc.is_valid():
            start_end = form_brix_alc.cleaned_data['brix_start_field'], form_brix_alc.cleaned_data['brix_end_field']
            if start_end[0] < start_end[1]:
                return JsonResponse({'success': False, 'error': 'Brixy początkowe nie mogą być większe od brixów końcowych'}, status=200)
            alcohol = BC.brix_to_percent(start_end[0], start_end[1])
            return JsonResponse({'success': True, 'alcohol': alcohol}, status=200)
        

        form_baling_alc = BalingToAlcoholForm(body)
        if form_baling_alc.is_valid():
            start_end = form_baling_alc.cleaned_data['baling_start_field'], form_baling_alc.cleaned_data['baling_end_field']
            if start_end[0] < start_end[1]:
                return JsonResponse({'success': False, 'error': 'Balingi początkowe nie mogą być większe od balingów końcowych'}, status=200)
            alcohol = BC.baling_to_percent(start_end[0], start_end[1])
            return JsonResponse({'success': True, 'alcohol': alcohol}, status=200)
        

        form_carbonation = CarbonationOfBeerForm(body)
        if form_carbonation.is_valid():
            co2 = form_carbonation.cleaned_data['co2_field']
            temperature = form_carbonation.cleaned_data['temperature_field']
            volume = form_carbonation.cleaned_data['beer_volume_field']
            blg_start = form_carbonation.cleaned_data['blg_start_field']
           
            glucose = BC.how_much_sugar(co2, volume, temperature)
            glucose_solution = BC.sugar_solution(blg_start, glucose)
            return JsonResponse({'success': True, 'glucose': glucose, 'glucose_solution': glucose_solution}, status=200)

    return render(
        request,
        'beer_calc/beer_calc.html',
        context = {
            'brix_to_blg': BrixToBlgForm(),
            'baling_to_brix': BlgToBrixForm(),
            'brix_alc': BrixToAlcoholForm(),
            'baling_alc': BalingToAlcoholForm(),
            'carbonation': CarbonationOfBeerForm(),

            'div_style': "max-width: 500px; background-color: rgb(255, 255, 255); margin: 1rem; padding: 15px; border-radius: 20px; width: 100vh;",

            'div_table_style': "max-width: 750px; background-color: rgb(255, 255, 255); margin: 1rem; padding: 15px; border-radius: 20px; width: 100vh;",

            'title_div': 'word-wrap text-break text-center text-dark mb-3',

            'beer_styles': [[nr, beer.style_name, beer.min_carbonation, beer.max_carbonation] for nr, beer in enumerate(BeerStyles.objects.all(), start= 1)],

            'icon': ButtonIcon.objects.last().photo.url,

            'search_form': SearchForm(),

            'site_name': 'PS | BeerCalc'
        }
    )

my_apps/templates/my_apps/meetings_day.html
{% if day == '00' %}
    <th></th>
{% else %}
    <th class="text-center flex-fill text-center text-light" style="margin: 0; padding: 0.15rem;" id="day_{{ date }}">
        <button class="btn btn-sm btn-{{ today_day }} mx-auto w-100 position-relative" type="button" data-bs-toggle="modal" data-bs-target="#{{ id }}">
            {% if event_counter %}
                {{ day }}
                <span class="position-absolute badge rounded-pill bg-{{ color }}">
                    {{ event_counter }}
                </span>
            {% else %}
                {{ day }} 
            {% endif %}
        </button>
    </th>
{% endif %}

my_apps/templates/my_apps/meetings_edit_new_event.html
{% extends 'my_apps/homepage_base.html' %}
{% block content %}


<div class="col-11 mx-auto" style="min-height: 100vh;">

    <div class="mb-2">
        <label class="h1">{{ title }}</label>
    </div>

    <form method="POST" class="bg-dark m-0" style="border-radius: 10px; padding: 1rem;">
        {% csrf_token %}
        <div class="mb-2">
            <small id="title-counter" class="text-muted bg-light p-1" style="border-radius: 10px;">0 / 40</small>
        </div>
        {{ form_event.event_title }}

        <div class="mb-2">
            <small id="location-counter" class="text-muted bg-light p-1" style="border-radius: 10px;">0 / 40</small>
        </div>
        {{ form_event.event_location }}

        <div class="mb-2">
            <small id="description-counter" class="text-muted bg-light p-1" style="border-radius: 10px;">0 / 200</small>
        </div>
        {{ form_event.event_description }}

        <div class="d-flex gap-3 mb-3">
            <div>
                {{ form_event.event_date }}
            </div>
            <div>
                {{ form_event.event_time }}
            </div>
        </div>

        <div style="margin-top: 2rem;">
            {% if not edit %}
                <label class="h1">Zaproś znajomego</label>
                <br>

                {% for friend in friends %}
                    <div class="form-check form-check-inline p-0 mt-2">
                        <input class="btn-check" type="checkbox" id="{{ friend.id }}" name="invited_friends" value="{{ friend.id }}">
                        <label class="btn btn-md btn-outline-success" for="{{ friend.id }}">{{ friend.username }}</label>
                    </div>
                {% endfor %}

            {% else %}
                <label class="h1">Dodaj lub usuń znajomego</label>
                <br>
                
                {{ friend_div|safe }}

                <script>
                    $(document).ready(function() {
                        $(document).on("click", "input[name='del_friend'], input[name='add_friend']", function(e) {
                            e.preventDefault();

                            const input = $(this);
                            const data = {};
                            data[input.attr("name")] = input.val();
                            data["csrfmiddlewaretoken"] = "{{ csrf_token }}";

                            $.ajax({
                                url: "{% url 'my_apps:meetings_edit_event' event_id %}",
                                type: "POST",
                                data: data,
                                success: function(response) {
                                    if (response.success) {
                                        $("#friend_div").empty();
                                        $("#friend_div").html(response.friend_div);
                                    }
                                },
                            });
                        });
                    });
                </script>

            {% endif %}
        </div>

        <div class="d-flex justify-content-end mx-auto gap-4" style="margin-top: 4rem;">
            {% if edit %}
                <button type="submit" class="btn btn-lg btn-primary" name="edit_event" value="{{ event_id }}">Zapisz</button>
            {% else %}
                <button type="submit" class="btn btn-lg btn-primary" name="new_event">Zapisz</button>
            {% endif %}


            <a href="{% url 'my_apps:meetings_calendar' %}">
                <button type="button" class="btn btn-lg btn-success">Wróć</button>
            </a>

            {% if edit %}
                <form method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-danger" name="del_event" value="{{ event_id }}">
                        Usuń
                    </button>
                </form>
            {% endif %}
        </div>

    </form>

</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        function setupCounter(inputId, counterId, maxLength) {
            const input = document.getElementById(inputId);
            const counter = document.getElementById(counterId);

            if (!input || !counter) return;

            function updateCounter() {
                const length = input.value.length;
                counter.textContent = `${length} / ${maxLength}`;
                if (length > maxLength) {
                    counter.classList.add('text-danger');
                } else {
                    counter.classList.remove('text-danger');
                }
            }

            input.addEventListener('input', updateCounter);
            updateCounter(); // Inicjalne zliczanie
        }

        setupCounter('id_event_title', 'title-counter', 40);
        setupCounter('id_event_location', 'location-counter', 40);
        setupCounter('id_event_description', 'description-counter', 200);
    });
</script>


{% endblock content %}

my_apps/templates/my_apps/meetings_month.html
<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-4 col-xxl-4" style="margin: 0rem; padding: 0.25rem;">
    <table class="table table-borderless text-light" style="margin: 0rem; padding: 0rem; table-layout: fixed; --bs-table-bg: rgba(0,0,0,0)">

        <thead>
            <div class="h1 text-center">
                {{ month }}
            </div>

            <tr class="border-bottom">
                {% for day in days %}
                    <th class="flex-fill text-center text-light">{{ day }}</th>
                {% endfor %}
            </tr>
        </thead>

        <tbody>
            {% for week in weeks %}
                <tr class="border border-0">
                    {% for day in week %}
                        {{ day|safe }}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

my_apps/templates/my_apps/meetings_new_event.html
{% extends "my_apps/homepage_base.html" %}

{% block content %}
<div class="col-11 mx-auto" style="min-height: 100vh;">

    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-{{ m.extra_tags }}" role="alert">{{ m }}</div>
        {% endfor %}
    {% endif %}

    <div class="dropdown text-center" style="margin-bottom: 1rem;">
        <label class="h2 m-0">
            Dodaj wydarzenie w 
            <button class="btn btn-lg btn-outline-light dropdown-toggle" style="padding: 0.25rem 0.5rem 0.35rem 0.5rem;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ year }}
            </button>
            <ul class="dropdown-menu">
                {% for y in year_range %}
                    <li><a class="dropdown-item" href="{% url 'my_apps:meetings_new_event' y %}">{{ y }}</a></li>
                {% endfor %}
            </ul>
        </label>
    </div>

    <form method="post">
        {% csrf_token %}
        <div>
            <label class="h3">
                {{ form_new_event.event_title.label }}
            </label>
            {{ form_new_event.event_title }}
        </div>
        
        <div>
            <label class="h3">
                {{ form_new_event.event_location.label }}
            </label>
            {{ form_new_event.event_location }}
        </div>
        
        <div>
            <label class="h3">
                {{ form_new_event.event_description.label }}
            </label>
            {{ form_new_event.event_description }}
        </div>
        
        <div>
            <label class="h3">
                {{ form_new_event.event_date.label }}
            </label>
            {{ form_new_event.event_date }}

            <button type="button" class="btn btn-md btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModalDate">
                Wybierz datę
            </button>
        </div>

        <div style="margin-top: 1rem;">
            <div class="dropdown">
                <div class="form-group d-flex flex-row flex-wrap">
                    <div class="flex-col m-1">
                        <label class="h2 m-0 p-0">
                            {{ form_new_event.event_time.label }}:
                        </label>
                    </div>

                    <div class="flex-col m-1">
                        <select class="form-select" name="selected_hour">
                            {% for h in hours %}
                                <option>{{ h }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="flex-col m-1">
                        <label class="h2 m-0 p-0">
                            :
                        </label>
                    </div>

                    <div class="flex-col m-1">
                        <select class="form-select" name="selected_minute">
                            {% for m in minutes %}
                                <option>{{ m }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="text-center mt-2 mb-2">
            <label class="h1">Zaproś znajomych</label>
            <div class="text-start d-flex flex-row flex-wrap mt-2" style="gap: 2rem;">
                {% for friend in friends %}
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="friends" value="{{ friend.id }}" id="friend{{ friend.id }}">
                        <label class="form-check-label h6" for="friend{{ friend.id }}">
                            {{ friend }}
                        </label>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="d-flex justify-content-end mb-3">
            <button class="btn btn-md btn-success" type="submit" name="new_event">
                Zapisz
            </button>

        </div>
    </form>

    <div class="d-flex justify-content-end">
        <a href="{% url 'my_apps:meetings_calendar' %}">
            <button class="btn btn-md btn-primary justify-content-end">
                Wróć
            </button>
        </a>
    </div>

</div>


<div class="modal fade text-dark" id="exampleModalDate" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content" style="max-height: 80%;">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Wybierz datę</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
                {% for month, weeks in calendar.items %}
                    <table class="table">
                        <thead>
                            <label class="h3">{{ month }}</label>

                            <tr class="border-bottom">
                                {% for day in days %}
                                    <th class="flex-fill text-center">{{ day }}</th>
                                {% endfor %}
                            </tr>
                        </thead>

                        <tbody>
                            {% for week in weeks %}
                                <tr>
                                    {% for day in week %}
                                        {% if day == '00' %}
                                            <th></th>
                                        {% else %}
                                            <th class="text-center" style="margin: 0; padding: 0.15rem;">
                                                <button data-bs-dismiss="modal" 
                                                {% if today_date.0 == year and today_date.1 == month and today_date.2 == day %}
                                                class="btn btn-sm btn-success date-link" 
                                                {% else %}
                                                class="btn btn-sm btn-primary date-link" 
                                                {% endif %}
                                                value="{{ day }}/{{ forloop.parentloop.parentloop.counter }}/{{ year }}" 
                                                style="width: 100%">
                                                    {{ day }}
                                                </button>
                                            </th>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<script>
    $(function() {
        // Funkcja, która reaguje na kliknięcie na datę
        $('.date-link').click(function(event) {
            event.preventDefault(); // Zatrzymuje domyślne zachowanie przycisku
            var dateParts = $(this).val().split('/');
            var selectedDate = dateParts[0] + '-' + dateParts[1].padStart(2, '0') + '-' + dateParts[2];
            $("#id_event_date").val(selectedDate);
        });
    });
</script>
{% endblock content %}