books/urls.py
from django.urls import path, include

from . import views

app_name = 'books'

urlpatterns = [
    path('books/', views.books, name= 'books')
]

currency_calc/urls.py
from django.urls import path


from . import views



app_name = 'currency_calc'
urlpatterns = [
    # path('currency_calc/', views.currency_calc, name='currency_calc'),
    # path('currency_calc/<str:parametr_result>/<str:parametr_message>/', views.currency_calc, name='currency_calc_with_params'),
    
    path('currency_calc/', views.currency_calc, name='currency_calc'),
    path('currency_calc/<str:date>', views.currency_calc, name='currency_calc'),
    path('currency_calc_records/', views.records, name='currency_calc_records'),
    path('currency_calc_sources/', views.sources, name='currency_calc_sources'),
    path('currency_calc_plots/', views.plots, name='currency_calc_plots'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('homepage.urls')),     
    # path('', include('meetings.urls')),     
    # path('', include('users.urls')),        
    # path('', include('beer_calc.urls')),        
    path('', include('my_apps.urls')),        
    path('', include('password_generator.urls')),        
    path('', include('currency_calc.urls')),        
    path('', include('rubikcube.urls')),        
    path('', include('flac_mp3_tag.urls')),        
    path('', include('deploying.urls')),        
    #path('', include('tests.urls')),          
    path('', include('checklist.urls')),       
    path('', include('user_data.urls')),       
    path('', include('split_the_bills.urls')),  
    path('', include('beer_calc.urls')),        
    path('', include('books.urls')),              
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

currency_calc/models.py
from django.db import models

# Create your models here.
class NBP_API(models.Model):
    id = models.AutoField(primary_key= True)
    date_addded = models.DateTimeField(auto_now= True)
    currencies = models.JSONField()

    class Meta:
        verbose_name = "NBP API"
        verbose_name_plural = "NBP API"

currency_calc/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.handlers.wsgi import WSGIRequest
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import QuerySet
from django.contrib import messages
from django.http import Http404

from .models import NBP_API
from .currency_calc import CurrencyCalc, CurrencyExchangeRatesSince2002

import pprint
import datetime
import plotly.express as px


# Create your views here.
def currency_calc(request: WSGIRequest, date: str = None):
    if 'dowloand_from_link' in request.POST and request.user.is_superuser:
        link = request.POST['dowloand_from_link']
        all_dates = [c.currencies['effectiveDate'] for c in NBP_API.objects.all()]
        currencies = CurrencyExchangeRatesSince2002().records(link= link)
        for currency in currencies:
            if currency['effectiveDate'] not in all_dates:
                NBP_API(currencies = currency).save()

    user = request.user
    context = {
        'user': request.user,
        'is_superuser': request.user.is_superuser,
        'records_len': NBP_API.objects.count() if NBP_API.objects.all() else 0,
    }
    
    if not context['records_len'] and not context['is_superuser']:
        raise Http404

    if date is not None:
        try: 
            date = str(datetime.datetime.strptime(date, "%Y-%m-%d").date())
            context['record'] = NBP_API.objects.get(currencies__effectiveDate = date).currencies
        except:
            context['record'] = NBP_API.objects.last().currencies
    else:
        if not context['records_len']:
            context['record'] = {"table": "", "no": "", "effectiveDate": "", "rates": []}
        else:
            context['record'] = NBP_API.objects.last().currencies

    context['date'] = context['record']['effectiveDate']

    for currency in context['record']['rates']:
        if 'country' in currency:
            currency['currency'] = currency['country']


    if user.is_superuser:
        CC2002: CurrencyExchangeRatesSince2002 = CurrencyExchangeRatesSince2002()
        context['all_links'] = CC2002.links_list()[::-1]


    if 'PLN_to_other' in request.POST or 'other_to_PLN' in request.POST:
        CC: CurrencyCalc = CurrencyCalc()
        
        code: str = request.POST['selected_currency']
        mid: list = [c['mid'] for c in context['record']['rates'] if c['code']==code][0]

        if 'PLN_to_other' in request.POST:
            pln = request.POST['PLN_to_other'].replace(',', '.')
            amount = CC.pln_to_other(pln, mid)
            mess = f"{pln} PLN = {amount} {code}"

        elif 'other_to_PLN' in request.POST:
            other = request.POST['other_to_PLN'].replace(',', '.')
            amount = CC.other_to_pln(other, mid)
            mess = f"{other} {code} = {amount} PLN"
        

        if amount is None:
            messages.warning(
                request= request,
                message= "Podaj prawidłową wartość",
                extra_tags= 'danger'
            )

        else:
            messages.success(
                request= request,
                message= mess,
                extra_tags= 'success'
            )



    return render(
        request= request,
        template_name= 'currency_calc/currency_calc_new.html',
        context= context,
    )


def records(request: WSGIRequest):

    return render(
        request= request,
        template_name= "currency_calc/currency_calc_records.html",
        context= {
            'records': NBP_API.objects.all().order_by('-currencies__effectiveDate')
        },
    )


def sources(request: WSGIRequest):

    links = CurrencyExchangeRatesSince2002().links_list()
    dates = [" - ".join(date.split("/")[-2:]) for date in links]

    date_link = {}
    for date, link in zip(dates, links):
        date_link[date] = link
    
    dates = {}
    for record in NBP_API.objects.all()[::-1]:
        year = datetime.datetime.strptime(record.currencies['effectiveDate'], "%Y-%m-%d").year
        if year not in dates:
            dates[year] = []
        dates[year].append(record.currencies['effectiveDate'])


    return render(
        request= request,
        template_name= "currency_calc/sources.html",
        context= {
            'date_link': date_link,
            'dates': dates,
        }
    )


def plots(request: WSGIRequest):
    selected_currency = request.POST.get(
        key = 'selected_currency',
        default = 'USD'
    )

    nbp_api: NBP_API = NBP_API

    all_currencies: dict = {c['code']: c['currency'] if 'currency' in c else c['country'] for c in nbp_api.objects.last().currencies['rates']}

    records: list[dict] = []
    for record in nbp_api.objects.order_by('currencies__effectiveDate'):
        for currency in record.currencies['rates']:

            if currency['code'] == selected_currency:
                mid = currency['mid']
                code = currency['code']
                country = currency['currency'] if 'currency' in currency else currency['country']

                records.append(
                    {
                        'date': f"{record.currencies['effectiveDate']}",
                        'currency': country,
                        'code': code,
                        'mid': float(mid),
                        'hover': f"{round(1 / mid, 4)} {selected_currency}",
                    }
                )
    
    start_date, end_date = records[0]['date'], records[-1]['date']
    
    plot = px.line(
        data_frame =    records,
        x =             'date',
        y =             'mid',
        hover_data =    ['hover'],
        title =         f'Średnie kursy walut dla: {selected_currency} [{all_currencies[selected_currency]}]',
        markers =       False,
        labels =        {
                            'date' : 'data',
                            'mid': 'średni kurs',
                            'hover': f'1 PLN'
                        },
        range_x =       [start_date, end_date],
        render_mode =   'webgl',   
        template =      'seaborn',
    ) \
    .update_layout(
        xaxis = dict(
            # rangeselector = dict(
            #     buttons = list(
            #             [
            #                 dict(count=(datetime.date.today() - datetime.date(2002, 1, 1)).days, label="all", step="day", stepmode="todate"),
            #                 dict(count=10, label="10y", step="year", stepmode="backward"),
            #                 dict(count=5, label="5y", step="year", stepmode="backward"),
            #                 dict(count=2, label="2y", step="year", stepmode="backward"),
            #                 dict(count=1, label="1y", step="year", stepmode="backward"),
            #                 dict(count=6, label="6m", step="month", stepmode="backward"),
            #                 dict(count=3, label="3m", step="month", stepmode="backward"),
            #                 dict(count=1, label="1m", step="month", stepmode="backward"),
            #             ]
            #         )
            #     ),
            rangeslider = dict(
                visible = True,
                range = [start_date, end_date],
                autorange = True,
                thickness = 0.1,
            ), 
            range = [start_date, end_date],
            type = 'date',
            #fixedrange = True, # zablokowanie możliwośc przesuwania wykresu w osi X
        )
    ).to_html()
    
    plot = f"""
    <div class="text-break word-wrap" style="min-width: 600px; min-height: 300px;">
        {plot}
    </div> 
    """

    return render(
        request= request,
        template_name= "currency_calc/plots.html",
        context= {
            'plot': plot,
            'all_currencies': all_currencies,
        }
    )

currency_calc/templates/currency_calc/currency_calc.html
{% extends 'my_apps/homepage_base.html' %}

{% block content %}
<div class="container-fluid text-dark text-center col-sm-12 col-md-10 col-lg-8 col-xl-7 col-xxl-6" style="margin: auto; min-height: 100vh">
    <div class="justify-content-center">

        <div class="bg-body-tertiary rounded bg-light" style="padding: 1rem; margin-top: 10rem; margin-bottom: 10rem;">
            {% if user.is_superuser %}
            <div>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class= "btn btn-sm btn-success" name="download_rates" style= "margin-top: 1rem;">Pobierz kursy</button>
                </form>
            </div>
            {% endif %}

            <div>
                <label class="h1 display-4 border-bottom">Kalkulator walutowy</label>
            </div>

            <div>
                <label class= "h6">Dane z dnia: {{ data_date }}</label>
            </div>

            <div style="margin-bottom: 2rem;">
                <label class= "h6"><a href="http://api.nbp.pl/api/exchangerates/tables/a/">Źródło danych</a></label>
            </div>


            {% if result is not None and message is not None%}
                {% if result == 'False' %}
                    <div class="alert alert-danger text-dark" role="alert">
                        {{ message }}
                    </div>
                {% elif result == 'True' %}
                    <div class="alert alert-success text-dark" role="alert">
                        {{ message }}
                    </div>
                {% endif %}
            {% endif %}

            <div style="margin-top: 2rem;">
                <form method="post">
                    {% csrf_token %}
                    <div style="margin: 1rem;">
                        <div>
                            <label class="h4 display-6">Przelicz PLN na inną walutę</label>
                        </div>

                        <div class="form-floating col-12">
                            <input type="text" class="form-control" name="PLN" id="PLN" placeholder="pln" value= {{ input_value1 }}>
                            <label for="PLN">Kwota w PLN</label>
                        </div>

                        <div class="input-group" style="margin-top: 1rem; margin-bottom: 1rem;">
                            <label class="input-group-text" for="inputGroupSelect01">Waluta</label>
                            <select class="form-select" id="inputGroupSelect01" name="selected_currency">
                                {% for currency in currencies %}
                                    {% if currency.code == currency_choose %}
                                        <option value= {{ currency.code }} selected >
                                    {% else %}
                                        <option value= {{ currency.code }}>
                                    {% endif %}
                                            {{ currency.code }} - {{ currency.currency.capitalize }} ({{ currency.mid }} PLN)
                                        </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-success btn" style="width: 100%;" name="PLN_to_other">Przelicz</button>
                        </div>
                    </div>
                </form>
            </div>

            <div style="margin-top: 5rem;">
                <form method="post">
                    {% csrf_token %}
                    <div style="margin: 1rem;">
                        <div>
                            <label class="h4 display-6">Przelicz inną walutę na PLN</label>
                        </div>

                        <div class="form-floating col-12">
                            <input type="text" class="form-control" name="Other" id="Other" placeholder="Other" value= {{ input_value2 }}>
                            <label for="Other">Kwota do przeliczenia na PLN</label>
                        </div>

                        <div class="input-group" style="margin-top: 1rem; margin-bottom: 1rem;">
                            <label class="input-group-text" for="inputGroupSelect01">Waluta</label>
                            <select class="form-select" id="inputGroupSelect01" name="selected_currency">
                                {% for currency in currencies %}
                                    {% if currency.code == currency_choose %}
                                        <option value= {{ currency.code }} selected >
                                    {% else %}
                                        <option value= {{ currency.code }}>
                                    {% endif %}
                                            {{ currency.code }} - {{ currency.currency.capitalize }} ({{ currency.mid }} PLN)
                                        </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-success btn" style="width: 100%;" name="other_to_PLN">Przelicz</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

currency_calc/templates/currency_calc/currency_calc_new.html
{% extends 'my_apps/homepage_base.html' %}

{% block content %}
<div class="container-fluid text-dark text-center col-sm-12 col-md-10 col-lg-8 col-xl-7 col-xxl-6" style="margin: auto; min-height: 100vh">
    <div class="justify-content-center">

        <div class="bg-body-tertiary rounded bg-light" style="padding: 1rem; margin-top: 10rem; margin-bottom: 10rem;"> 
            {% if user.is_superuser %}
            <div style="display: flex; flex-wrap: wrap; gap: 1rem; justify-content: center;">
                <button class="btn btn-sm btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#all_links" aria-expanded="false" aria-controls="all_links">
                    Wszystkie linki
                </button>
            </div>

            <div class="collapse" id="all_links" style="margin-top: 1rem;">
                <div class="card card-body" style="display: flex; flex-wrap: wrap;">
                    {% for link in all_links %}
                        <div style="display: flex; flex-wrap: wrap; padding: 0.5rem; gap: 0.25rem;">
                            <form method="post" style="padding: 0; margin: 0rem; flex-grow: 1;">
                                {% csrf_token %}
                                <button class="btn btn-sm btn-primary text-break" name="dowloand_from_link" type="submit" value="{{ link }}">
                                    {{ forloop.counter }} {{ link }}
                                </button>
                            </form>
                            
                            <div style="padding: 0; margin: 0;">
                                <button class="btn btn-sm btn-success">
                                    <a href="{{ link }}" target="_blank" style="text-decoration: none;" class="text-light">
                                            Otwórz
                                    </a>
                                </button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %} 

            <div>
                <label class="h1 display-4 border-bottom">Kalkulator walutowy</label>
            </div>

            <div>
                <label class= "h6">Dane z dnia: {{ date }}</label>
            </div>

            <div>
                <label class= "h6">
                    <a href="{% url 'currency_calc:currency_calc_sources' %}" target="_blank">
                        Źródła danych / Zmień datę
                    </a>
                </label>
            </div>

            <div>
                <label class= "h6">
                    <a href="{% url 'currency_calc:currency_calc_plots' %}" target="_blank">
                        Wizualizacja danych
                    </a>
                </label>
            </div>

            <div style="margin-bottom: 2rem;">
                <label class= "h6">
                    <a href="{% url 'currency_calc:currency_calc_records' %}" target="_blank">
                        Wszystkie rekordy [{{ records_len }}]
                    </a>
                </label>
            </div>

            {% if messages %}
                {% for m in messages %}
                    <div class="col-11 justify-content-center mx-auto alert alert-{{ m.extra_tags }} text-dark text-break word-wrap">
                        <label class="h1">{{ m }}</label>
                    </div>
                {% endfor %}
            {% endif %}

            <div style="margin-top: 2rem;">
                <form method="post">
                    {% csrf_token %}
                    <div style="margin: 1rem;">
                        <div>
                            <label class="h4 display-6">Przelicz PLN na inną walutę</label>
                        </div>

                        <div class="form-floating col-12">
                            <input type="text" class="form-control" name="PLN_to_other" id="PLN" placeholder="pln" value= {{ input_value1 }}>
                            <label for="PLN">Kwota w PLN</label>
                        </div>

                        <div class="input-group" style="margin-top: 1rem; margin-bottom: 1rem;">
                            <label class="input-group-text" for="inputGroupSelect01">Waluta</label>
                            <select class="form-select" id="inputGroupSelect01" name="selected_currency">
                                {% for currency in record.rates %}
                                    {% if currency.code == 'USD' %}
                                        <option value= {{ currency.code }} selected >
                                    {% else %}
                                        <option value= {{ currency.code }}>
                                    {% endif %}
                                            {{ currency.code }} - {{ currency.currency.capitalize }} ({{ currency.mid }} PLN)
                                        </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-success btn" style="width: 100%;">Przelicz</button>
                        </div>
                    </div>
                </form>
            </div>

            <div style="margin-top: 5rem;">
                <form method="post">
                    {% csrf_token %}
                    <div style="margin: 1rem;">
                        <div>
                            <label class="h4 display-6">Przelicz inną walutę na PLN</label>
                        </div>

                        <div class="form-floating col-12">
                            <input type="text" class="form-control" name="other_to_PLN" id="Other" placeholder="Other" value= {{ input_value2 }}>
                            <label for="Other">Kwota do przeliczenia na PLN</label>
                        </div>

                        <div class="input-group" style="margin-top: 1rem; margin-bottom: 1rem;">
                            <label class="input-group-text" for="inputGroupSelect01">Waluta</label>
                            <select class="form-select" id="inputGroupSelect01" name="selected_currency">
                                {% for currency in record.rates %}
                                    {% if currency.code == 'USD' %}
                                        <option value= {{ currency.code }} selected >
                                    {% else %}
                                        <option value= {{ currency.code }}>
                                    {% endif %}
                                            {{ currency.code }} - {{ currency.currency.capitalize }} ({{ currency.mid }} PLN)
                                        </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div>
                            <button type="submit" class="btn btn-success btn" style="width: 100%;">Przelicz</button>
                        </div>
                    </div>
                </form>
            </div>

            {% comment %} 
            <div class="" style="margin-top: 5rem;">
                <button class="btn btn-lg btn-outline-dark dropdown-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Wybierz dane z innego dnia
                </button>
            </div>

            <div class="collapse" id="collapseExample">
                <div class="d-flex flex-wrap flex-row justify-content-center mx-auto" style="margin-top: 1rem;">
                    {% for r in records %}
                        <form method="POST" class="m-1 p-0">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-primary" type="submit" value="{{ r.id }}" name="select_data">
                                {{ r.currencies.effectiveDate }}
                            </button> 
                        </form>
                    {% endfor %}
                </div>
            </div> 
            {% endcomment %}

            <div style="margin-top: 5rem;">
                <label class="display-6">Kod Pythona, którym pobierzesz wszystkie rekordy:</label>

                <div class="text-start user-select-all" style="background-color: black; color: white; border-radius: 10px; padding: 1rem; margin-top: 1rem;">
                    <pre style="margin: 0; padding: 0;"><code># Wersja Pythona: 3.11.1
# pip install requests==2.30.0 beautifulsoup4==4.12.3
import bs4
import json
import requests

def all_records() -> list[dict]:
    url = "https://www.pskrzynski.pl/currency_calc_records/"

    get = requests.get(url= url).text

    bs = bs4.BeautifulSoup(get, "html.parser") \
        .find_all('div', {'class': 'record'})

    records = []
    for b in bs:
        b: bs4.element.Tag

        s = str(b.contents[0]) \
            .strip() \
            .replace("'", '"')
        
        records.append(
            json.loads(s)
        )
    return records</code></pre>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

currency_calc/templates/currency_calc/currency_calc_records.html
<body style="padding: 0; margin: 0; background-color: #1c1c1c; color: #ffffff;">
    <div style="margin: 0; padding: 12;">
        {% for r in records %}
            <div class="record" style="margin-bottom: 1rem;">
                {{ r.currencies }}
            </div>
        {% endfor %}
    </div>
</body>

currency_calc/templates/currency_calc/plots.html
{% extends 'my_apps/homepage_base.html' %}

{% block content %}
<div class="col-11 mx-auto justify-content-center" style="min-height: 100vh;">
    <div>
        <button class="btn btn-primary" style="margin-bottom: 1rem;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Wybierz walutę
        </button>
        
        <div class="collapse" id="collapseExample" style="margin-top: 1rem; margin-bottom: 1rem;">    
            <div class="card card-body">
                <div style="display: flex; flex-wrap: wrap; gap: 1rem;">
                    {% for key, value in all_currencies.items %}
                        <form method="POST" style="margin: 0; padding: 0;">
                            {% csrf_token %}
                            <button class="btn btn-sm btn-primary" type="submit" name="selected_currency" value="{{ key }}">
                                {{ key }} - {{ value }}
                            </button>
                        </form>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div id="plot" style="overflow-x: auto;">
        {{ plot|safe }}
    </div>
</div>
{% endblock content %}

currency_calc/templates/currency_calc/sources.html
{% extends 'my_apps/homepage_base.html' %}

{% block content %}
<div class="col-11 mx-auto justify-content-center" style="min-height: 100vh;">
    <div>
        <label class="display-1">Źródła danych</label>
    </div>

    <div style="margin-top: 4rem;">
        <label class="display-6 mt-4">API: Wybierz zakres danych</label>
    </div>

    <div style="display: flex; flex-wrap: wrap; gap: 1rem; margin-top: 2rem;">
        {% for date, link in date_link.items %}
            <button class="btn btn-sm btn-primary">
                <a href="{{ link }}" target="_blank" class="text-light text-decoration-none">
                    {{ date }}
                </a>
            </button>
        {% endfor %}
    </div>

    <div style="margin-top: 4rem;">
        <label class="display-6">Kalkulator: Wybierz dane z dnia</label>
    </div>

    <div>
        {% for year, dates in dates.items %}
            <div style="margin-top: 2rem;">
                <label class="h3">
                    {{ year }}
                </label>
            </div>

            <div style="display: flex; flex-wrap: wrap; gap: 1rem;">
                {% for date in dates %}
                <button class="btn btn-sm btn-primary">
                    <a href="{% url 'currency_calc:currency_calc' date %}" target="_blank" class="text-light text-decoration-none">
                        {{ date }}
                    </a>
                </button>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}